language: node_js
node_js:
  - "7.8"
os:
  - osx
git:
  submodules: false
before_install:
  - git submodule update --init --remote --recursive
env:
  - TEST_SUITE=units
  - TEST_SUITE=integration
script: "npm run test:$TEST_SUITE"

